### ISSUE TITLE
Imágenes productos

### ISSUE THREAD

**Issue by NicoGonzalez94** [JBjuliobotta/Snacky#28]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que las imágenes de los productos se puedan visualizar correctamente.
• Ya que las imágenes no cargan correctamente, encontrar un texto descriptivo de la imagen.

## Resultado actual

• Las imágenes no se muestran ni cargan.
• No se encuentra texto descriptivo de la imagen (Atributo alt).

## Captura

![image](https://github.com/JBjuliobotta/Snacky/assets/166792979/fd37b65b-f8a5-4483-8b75-e59b4d403f72)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by JBjuliobotta** [comment]
El resto de los errores ya están corregidos. Las imágenes ya tienen el atributo alt correctamente codeado. Lo que no puedo resolver es porqué a algunas personas le cargan la imágenes de los productos y a otras no, en mi ordenador se ven tanto en localhost, cómo abriendo la app desde netlify.
